### ISSUE TITLE
Code to be removed

### ISSUE THREAD

**Issue by pkrog** [erwannbla/cours-python-avance#1]
I think this old code should be removed, it makes the screen flicker:
https://github.com/erwannbla/cours-python-avance/blob/64be9ddf885b8b8490da6b8a1f808aec2cc159f6/snake/snake.py#L65-L66

**Comment by erwannbla** [comment]
cependant si j'enleve ces lignes, le damier ne s'affiche pas ensuite ? Je n'ai pas compris cela donc j'ai laisse le remplissage en noir

**Comment by pkrog** [comment]
La couleur (255,255,255) est la couleur blanche.
(0,0,0) est la couleur noire.
Je vois qu'effectivement tu ne colories que les cases noires dans tes deux boules (for i ... for j ...), donc il te faut d'abord le fond blanc.
Par contre tu as deux fois l'appelle `pg.display.update()`. Il faut éliminer le premier, et garder seulement le deuxième qui est à la fin. Cet appelle sert à provoquer l'affichage de ce que tu as dessiné sur l'objet `screen`. Si tu appelles deux fois la fonction avec deux dessins différents cela donne cet effet de scintillement.
