### ISSUE TITLE
Misuse of arguments

### ISSUE THREAD

**Issue by pkrog** [erwannbla/cours-python-avance#2]
Wrong usage of command line values:
https://github.com/erwannbla/cours-python-avance/blob/64be9ddf885b8b8490da6b8a1f808aec2cc159f6/snake/snake.py#L12-L16

When I run `snake.py --height 300`, the game quit immediately.
When I run `snake.py --width 300 --widthpixel 10`, I get the following screen:
![Screenshot from 2022-11-01 21-42-04](https://user-images.githubusercontent.com/15377906/199336963-2add8b8f-2256-4236-9ee3-06da04cb7e31.png)

**Comment by erwannbla** [comment]
je pense qu'ici le probleme est que vous avez (implicitement) choisi des pixels rectangulaires (et non carres) pour le jeu

**Comment by pkrog** [comment]
Je pense que le problème vient de ce que ton jeu accepte deux valeurs différentes pour la largeur et la hauteur des cases.
Les spécifications sont une choses, et ton application réelle une autre.
Ton application doit s'attendre à recevoir toutes sortes d'entrées (de la part d'un humain ou d'un autre programme). Il faut donc vérifier leurs valeurs. Ici tu proposes deux valeurs pour la largeur et la hauteur, un utilisateur peut donc fournir deux valeurs différentes. À ton programme de se prémunir contre des cas qu'il ne sait pas gérer en refusant les valeurs et en affichant un message d'erreur. Tu peux alors soit terminer le programme, soit continuer en utilisant des valeurs par défaut que tu sais correct, ou en utilisant seulement la largeur ou la hauteur.
De même que se passe-t-il si l'on fournit une largeur de case qui n'est pas un diviseur de la largeur de la fenêtre ?
